"""initial_schema

Revision ID: 62ffb999d45a
Revises:
Create Date: 2026-04-06 23:12:43.284389
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "62ffb999d45a"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "archived_articles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("synopsis", sa.Text(), nullable=False),
        sa.Column("author", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("source_name", sa.Text(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("inshorts_url", sa.Text(), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("entities", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("noun_phrases", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("language", sa.String(length=10), nullable=True),
        sa.Column("is_duplicate", sa.Boolean(), nullable=True),
        sa.Column("duplicate_of", sa.UUID(), nullable=True),
        sa.Column("bias_score", sa.Float(), nullable=True),
        sa.Column("bias_label", sa.String(length=20), nullable=True),
        sa.Column("sentiment_score", sa.Float(), nullable=True),
        sa.Column("sentiment_label", sa.String(length=20), nullable=True),
        sa.Column("bias_types", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("flagged_tokens", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("trust_score", sa.Float(), nullable=True),
        sa.Column("source_credibility_tier", sa.String(length=20), nullable=True),
        sa.Column("top_claims", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reliability_score", sa.Float(), nullable=True),
        sa.Column("analysis_status", sa.String(length=20), nullable=True),
        sa.Column("scraped_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("analyzed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "archived_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_archived_articles_content_hash"),
        "archived_articles",
        ["content_hash"],
        unique=False,
    )
    op.create_table(
        "articles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("synopsis", sa.Text(), nullable=False),
        sa.Column("author", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("source_name", sa.Text(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("inshorts_url", sa.Text(), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("entities", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("noun_phrases", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("language", sa.String(length=10), nullable=True),
        sa.Column("is_duplicate", sa.Boolean(), nullable=True),
        sa.Column("duplicate_of", sa.UUID(), nullable=True),
        sa.Column("bias_score", sa.Float(), nullable=True),
        sa.Column("bias_label", sa.String(length=20), nullable=True),
        sa.Column("sentiment_score", sa.Float(), nullable=True),
        sa.Column("sentiment_label", sa.String(length=20), nullable=True),
        sa.Column("bias_types", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("flagged_tokens", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("trust_score", sa.Float(), nullable=True),
        sa.Column("source_credibility_tier", sa.String(length=20), nullable=True),
        sa.Column("top_claims", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reliability_score", sa.Float(), nullable=True),
        sa.Column("analysis_status", sa.String(length=20), nullable=True),
        sa.Column(
            "scraped_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("analyzed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_articles_category", "articles", ["category"], unique=False)
    op.create_index(op.f("ix_articles_content_hash"), "articles", ["content_hash"], unique=True)
    op.create_index("ix_articles_published_at", "articles", ["published_at"], unique=False)
    op.create_index(
        "ix_articles_reliability_score", "articles", ["reliability_score"], unique=False
    )
    op.create_index("ix_articles_scraped_at", "articles", ["scraped_at"], unique=False)
    op.create_index("ix_articles_status", "articles", ["status"], unique=False)
    op.create_table(
        "sources",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("credibility_tier", sa.String(length=20), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("bias_tendency", sa.String(length=20), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "analysis_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("article_id", sa.UUID(), nullable=False),
        sa.Column("model_name", sa.String(length=200), nullable=False),
        sa.Column("model_version", sa.String(length=100), nullable=True),
        sa.Column("raw_output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "run_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_analysis_runs_article_id", "analysis_runs", ["article_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_analysis_runs_article_id", table_name="analysis_runs")
    op.drop_table("analysis_runs")
    op.drop_table("sources")
    op.drop_index("ix_articles_status", table_name="articles")
    op.drop_index("ix_articles_scraped_at", table_name="articles")
    op.drop_index("ix_articles_reliability_score", table_name="articles")
    op.drop_index("ix_articles_published_at", table_name="articles")
    op.drop_index(op.f("ix_articles_content_hash"), table_name="articles")
    op.drop_index("ix_articles_category", table_name="articles")
    op.drop_table("articles")
    op.drop_index(op.f("ix_archived_articles_content_hash"), table_name="archived_articles")
    op.drop_table("archived_articles")
    # ### end Alembic commands ###
